fiftyshades = [

"Some girls are happy just to stimulate the genitals through phalangetic motion when they're alone, but I can't get off without having a 10 inch purple battery-operated monster in my gaping clam cavern and an antique doorknob up my brown eye. Leaving my panties sunny side up on the floor was the least of my worries as his timed slimer probed deeper into my marmite motorway. The mixture of Mr. Hanky and gentleman's relish in my Mavis Fritter created the delicious rectal stew that he was so fond of. There was magician's wax haemorrhaging from his pink tractor beam and I was wetter than an Italian cruise ship. We were ready for more. It was bliss having his disco stick slid inside me again; stuffing my clam-flavoured pothole with my fist just didn't get my bearded haddock pasty squirting like it used to.",

"With my vertical garden now much like a stuntman's knee, he thought it was time to start plunging my shit winker. Is now the time to tell him I really need to arc a toilet twinkie, I wondered? He extruded a giant butt nugget on my mosquito bites just so he could lap it up like a bulldog eating porridge. With his flesh gordon hammering deep into my chlamydia canal, the sensation of his eight inches of throbbing pink jesus smashing my cervix made me quiver like Muhammad Ali on a tumble dryer. The seemingly never-ending streams of love mayonnaise emanating from his tallywacker soon had me coated like a plasterer's radio. The feeling of his Da Vinci load frothing down my throat got my vertical moisture flowing quicker than a greased weasel shit.",

"When he removed his wensleydale wand from my vintage golf bag, he was pleasantly surprised to see a butt nugget staring back as him. He knew I couldn't wait to suck the stink pickle off his vein cane. The seemingly never-ending streams of ectoplasm emanating from his womb raider soon had me coated like a plasterer's radio. My quim was trembling like jelly. Hours of thrusting like this would leave any girl's piss flaps looking like Terry Waite's allotment, and I was no different! He pitched a giant butt nugget on my rack just so he could devour it up like a bulldog eating porridge.",

"The unrelenting orgasms from his sperminator raiding my furry cup made me come so hard, I began sweating like Joseph Fritzel on Cribs. Leaving my panties sunny side up on the floor was the least of my worries as his veiny quim prod slid deeper into my turd cutter. Hours of slamming like this would leave any girl's panty hamster looking like a motorway pileup, and I was no different! There was man fat oozing from his disco stick and I was wetter than an Italian cruise ship. We were ready for more. Inserting a gerbil into my oyster ditch got me spattering vertical moisture faster than snot off a whip.",

"The mixture of toilet twinkie and love mayonnaise in my Oxo orifice created the delicious porthole pudding that he was so fond of. After having my hatchet wound pounded, he then proceeded to raid my chocolate starfish. With his battering ram pounding deep into my hatchet wound, the sensation of his brie baton smashing my cervix made me quiver like a rat on acid. I awoke the next morning with my pink velvet sausage wallet still dripping. I thought it was over but his all-beef thermometer had other ideas. My mouth was so full of pink tractor beam and baby gravy, the steamin' semen was frothing down my chin and onto my boobage.",

"When he removed his blood-engorged mayonnaise cannon from my poop chute, he was pleasantly surprised to see a sewer trout staring back as him. He knew I couldn't wait to consume the footlong fudge bullet off his cunt stretcher. My fuck gutter was trembling like jelly. It was bliss having his skin flute slid inside me again; stuffing my meat purse with a 10 inch purple battery-operated monster just didn't get my ground zero grotto spritzing like it used to. He munched on my meaty hangers, even though I'd been on the rag for the best part of a week. Inserting a barbie doll into my cock holster got me surging spaff faster than greased shit off a shiny shovel.",

"Inserting a 9-iron into my gashtray got me ejecting spaff faster than greased shit off a shiny shovel. Hours of hammering like this would leave any girl's vertical smile looking like a manatee in yoga pants, and I was no different! The raiding of my poo pipe was so vigorous, he soon found his kids on a swing joining his Nelson's Column deep in my fudge factory. By now, my vibration station was oozing like there was a midget inside me with a super soaker. With his one-eyed milkman raiding deep into my wunder down under, the sensation of his eight inches of throbbing pink jesus smashing my cervix made me quake like Micheal J. Fox licking a car battery.",

"By now, my cod canyon was dripping like a slavering dog. There was ectoplasm trickling from his cunt stretcher and I was wetter than a bathmaid's elbow. We were ready for more. The seemingly never-ending streams of Da Vinci load emanating from his long-dong silver soon had me coated like a plasterer's radio. I awoke the next morning with my split peach still leaking. I thought it was over but his tenderloin truncheon had other ideas. Some girls are happy just to study english cliterature when they're alone, but I can't get off without having an egg timer in my bearded haddock pasty and a squash up my soft tight anus.",

"Some girls are happy just to buff the muff when they're alone, but I can't get off without having a squash in my clam-flavoured pothole and a 10 inch purple battery-operated monster up my cocoa channel. It was bliss having his blood-engorged mayonnaise cannon stuffed inside me again; stuffing my wizards sleeve with a lightbulb just didn't get my sperm socket splurging like it used to. I can't wait to devour the baby gravy from his cunt stretcher. By now, my split peach was draining like Adele waiting for Greggs to open. With his love muscle hammering deep into my sperm socket, the sensation of his piss pipe smashing my cervix made me quake like jelly.",

"The slamming of my other vagina was so vigorous, he soon found his family jewels joining his pink tractor beam deep in my marmite motorway. Hours of slamming like this would leave any girl's open-faced ham sandwich looking like a stuntman's knee, and I was no different! The seemingly never-ending streams of cock snot emanating from his Nelson's Column soon had me coated like a plasterer's radio. He cut a giant colon cobra on my cans just so he could devour it up like a pig at a trough. I can't wait to suck the penis pudding from his chorizo howitzer."

]